# language: pt
# charset: UTF-8

Funcionalidade: Avaliação Risco de Crédito

  Contexto: Acessar o site Gestor de Crédito
    Dado Eu acesso a home do site
    Quando Eu informo dados de login válidos
    Então eu devo acessar a home e ver uma mensagem com o nome de usuário


  Esquema do Cenário: Criar análise de crédito com sucesso "CMA-PJ" - <CT>
    Dado eu acesso a tela de análise de crédito
    E configuro a massa com os dados CMA-PJ: "<CNPJ>", "<DATA_ALT>", "<CAMPO_SCORE>", "<VALOR_SCORE>"
    Quando informo os seguintes dados on-line e clico em Analisar: "<CNPJ>","<VALOR_NF>","<AUTO_FALENCIA>","<CONCORDATA>","<CONCORDATA_DEFERIDA>","<CONCORDATA_REQUERIDA>","<CONCORDATA_SUSPENSIVA>","<DATA_ENTRADA_SOCIO_MAIS_RECENTE>","<DATA_DE_INICIO_DA_ATIVIDADE>","<DATA_DO_SISTEMA>","<FALENCIA_DECRETADA>","<FALENCIA_REQUERIDA>","<HISTORICO_DE_ATRASOS>","<MODALIDADE_DE_PAGAMENTO>","<PARTICIPACAO_EM_FALENCIA>","<QT_REFIN_BANCOS>","<RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA>","<RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA>","<RECUPERACAO_JUDICIAL_CONCEDIDA>","<RECUPERACAO_JUDICIAL_REQUERIDA>","<STATUS_CNPJ>","<TEMPO_RELACIONAMENTO>","<VALORES_EM_ABERTO>","<VR_REFIN_BANCOS_ATE_A_DATA>"
    Entao eu devo ver uma página com o resultado da análise: "<MSG_RESULTADO_ANALISE>", "<VALOR_NF>"
    E no relatório de Decisão de Crédito ter os seguintes dados on-line validados: "<CNPJ>","<VALOR_NF>","<AUTO_FALENCIA>","<CONCORDATA>","<CONCORDATA_DEFERIDA>","<CONCORDATA_REQUERIDA>","<CONCORDATA_SUSPENSIVA>","<DATA_ENTRADA_SOCIO_MAIS_RECENTE>","<DATA_DE_INICIO_DA_ATIVIDADE>","<DATA_DO_SISTEMA>","<FALENCIA_DECRETADA>","<FALENCIA_REQUERIDA>","<HISTORICO_DE_ATRASOS>","<MODALIDADE_DE_PAGAMENTO>","<PARTICIPACAO_EM_FALENCIA>","<QT_REFIN_BANCOS>","<RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA>","<RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA>","<RECUPERACAO_JUDICIAL_CONCEDIDA>","<RECUPERACAO_JUDICIAL_REQUERIDA>","<STATUS_CNPJ>","<TEMPO_RELACIONAMENTO>","<VALORES_EM_ABERTO>","<VR_REFIN_BANCOS_ATE_A_DATA>"

    Exemplos:
      | CT      | CNPJ               | VALOR_NF | AUTO_FALENCIA | CONCORDATA | CONCORDATA_DEFERIDA | CONCORDATA_REQUERIDA | CONCORDATA_SUSPENSIVA | DATA_ENTRADA_SOCIO_MAIS_RECENTE | DATA_DE_INICIO_DA_ATIVIDADE | DATA_DO_SISTEMA | FALENCIA_DECRETADA | FALENCIA_REQUERIDA | HISTORICO_DE_ATRASOS | MODALIDADE_DE_PAGAMENTO | PARTICIPACAO_EM_FALENCIA | QT_REFIN_BANCOS | RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA | RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA | RECUPERACAO_JUDICIAL_CONCEDIDA | RECUPERACAO_JUDICIAL_REQUERIDA | STATUS_CNPJ | TEMPO_RELACIONAMENTO | VALORES_EM_ABERTO | VR_REFIN_BANCOS_ATE_A_DATA | MSG_RESULTADO_ANALISE                                                                        | DATA_ALT   | CAMPO_SCORE                       | VALOR_SCORE |
      | BUNZL01 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | #                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | INATIVO     | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA: RETAGUARDA - STATUS CNPJ DIFERENTE DE ATIVO NA RECEITA FEDERAL     | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           |
      | BUNZL02 | 61.585.865/0001-51 | 100,00   | SIM           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | #                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA: RETAGUARDA - CNPJ COM OCORRÊNCIA DE AUTO FALÊNCIA                  | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           |
      | BUNZL03 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | SIM                | NÃO                | #                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA: RETAGUARDA - CNPJ COM OCORRÊNCIA DE FALÊNCIA DECRETADA             | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           |
      | BUNZL04 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | #                    | Boleto                  | SIM                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA: RETAGUARDA - CNPJ COM OCORRÊNCIA DE PARTICIPAÇÃO EM FALÊNCIA       | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           |
      | BUNZL05 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | SIM                | #                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA: RETAGUARDA - CNPJ COM OCORRÊNCIA DE FALÊNCIA REQUERIDA             | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           |
      | BUNZL06 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | SIM                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | #                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA: RETAGUARDA - CNPJ COM OCORRÊNCIA DE CONCORDATA REQUERIDA           | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           |
      | BUNZL07 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | SIM                   | #                               | #                           | #               | NÃO                | NÃO                | #                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA: RETAGUARDA - CNPJ COM OCORRÊNCIA DE CONCORDATA SUSPENSIVA          | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           |
      | BUNZL08 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | #                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | SIM                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA: RETAGUARDA - CNPJ COM OCORRENCIA DE RECUPERAÇÃO JUDICIAL CONCEDIDA | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           |
      | BUNZL09 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | #                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | SIM                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA: RETAGUARDA - CNPJ COM OCORRÊNCIA DE RECUPERAÇÃO JUDICIAL REQUERIDA | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           |
      | BUNZL10 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | 01/07/2020                      | #                           | 01/01/2020      | NÃO                | NÃO                | #                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA: RETAGUARDA - CNPJ COM ALTERAÇÃO RECENTE NO QUADRO SOCIETÁRIO       | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           |
      | BUNZL11 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | #                    | Boleto                  | NÃO                      | 1               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA: RETAGUARDA - CNPJ COM REFIN ATIVO                                  | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           |
      | BUNZL12 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | #                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA: RETAGUARDA - CNPJ COM SCORE DEFAULT                                | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | 1           |

  Esquema do Cenário: Criar análise de crédito com sucesso "Classificação Risco Zero" - <CT>
    Dado eu acesso a tela de análise de crédito
    E configuro a massa com os dados (Classificação Risco Zero): "<CNPJ>","<DATA_ALT>","<CAMPO_SCORE>","<VALOR_SCORE>","<CAMPO_PAGTOS_PONTUAIS>","<VALOR_PAGTOS_PONTUAIS>","<CAMPO_CONSULTAS_MES_ATUAL>","<VALOR_CONSULTAS_MES_ATUAL>","<CAMPO_CONSULTAS_MES_ANTERIOR>","<VALOR_CONSULTAS_MES_ANTERIOR>"
    Quando informo os seguintes dados on-line e clico em Analisar: "<CNPJ>","<VALOR_NF>","<AUTO_FALENCIA>","<CONCORDATA>","<CONCORDATA_DEFERIDA>","<CONCORDATA_REQUERIDA>","<CONCORDATA_SUSPENSIVA>","<DATA_ENTRADA_SOCIO_MAIS_RECENTE>","<DATA_DE_INICIO_DA_ATIVIDADE>","<DATA_DO_SISTEMA>","<FALENCIA_DECRETADA>","<FALENCIA_REQUERIDA>","<HISTORICO_DE_ATRASOS>","<MODALIDADE_DE_PAGAMENTO>","<PARTICIPACAO_EM_FALENCIA>","<QT_REFIN_BANCOS>","<RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA>","<RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA>","<RECUPERACAO_JUDICIAL_CONCEDIDA>","<RECUPERACAO_JUDICIAL_REQUERIDA>","<STATUS_CNPJ>","<TEMPO_RELACIONAMENTO>","<VALORES_EM_ABERTO>","<VR_REFIN_BANCOS_ATE_A_DATA>"
    Entao eu devo ver uma página com o resultado da análise: "<MSG_RESULTADO_ANALISE>", "<VALOR_NF>"
    E no relatório de Decisão de Crédito ter os seguintes dados on-line validados: "<CNPJ>","<VALOR_NF>","<AUTO_FALENCIA>","<CONCORDATA>","<CONCORDATA_DEFERIDA>","<CONCORDATA_REQUERIDA>","<CONCORDATA_SUSPENSIVA>","<DATA_ENTRADA_SOCIO_MAIS_RECENTE>","<DATA_DE_INICIO_DA_ATIVIDADE>","<DATA_DO_SISTEMA>","<FALENCIA_DECRETADA>","<FALENCIA_REQUERIDA>","<HISTORICO_DE_ATRASOS>","<MODALIDADE_DE_PAGAMENTO>","<PARTICIPACAO_EM_FALENCIA>","<QT_REFIN_BANCOS>","<RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA>","<RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA>","<RECUPERACAO_JUDICIAL_CONCEDIDA>","<RECUPERACAO_JUDICIAL_REQUERIDA>","<STATUS_CNPJ>","<TEMPO_RELACIONAMENTO>","<VALORES_EM_ABERTO>","<VR_REFIN_BANCOS_ATE_A_DATA>"
    E no relatório de Decisão de Crédito ter os seguintes dados (Classificação Risco Zero) validados: "<VALOR_SCORE>","<VALOR_PAGTOS_PONTUAIS>","<VALOR_CONSULTAS_MES_ATUAL>","<VALOR_CONSULTAS_MES_ANTERIOR>","<PONTUACAO>"

    Exemplos:
      | CT      | CNPJ               | VALOR_NF | AUTO_FALENCIA | CONCORDATA | CONCORDATA_DEFERIDA | CONCORDATA_REQUERIDA | CONCORDATA_SUSPENSIVA | DATA_ENTRADA_SOCIO_MAIS_RECENTE | DATA_DE_INICIO_DA_ATIVIDADE | DATA_DO_SISTEMA | FALENCIA_DECRETADA | FALENCIA_REQUERIDA | HISTORICO_DE_ATRASOS | MODALIDADE_DE_PAGAMENTO | PARTICIPACAO_EM_FALENCIA | QT_REFIN_BANCOS | RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA | RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA | RECUPERACAO_JUDICIAL_CONCEDIDA | RECUPERACAO_JUDICIAL_REQUERIDA | STATUS_CNPJ | TEMPO_RELACIONAMENTO | VALORES_EM_ABERTO | VR_REFIN_BANCOS_ATE_A_DATA | MSG_RESULTADO_ANALISE    | PONTUACAO | DATA_ALT   | CAMPO_SCORE                       | VALOR_SCORE | CAMPO_PAGTOS_PONTUAIS | VALOR_PAGTOS_PONTUAIS | CAMPO_CONSULTAS_MES_ATUAL    | VALOR_CONSULTAS_MES_ATUAL | CAMPO_CONSULTAS_MES_ANTERIOR | VALOR_CONSULTAS_MES_ANTERIOR |
      | BUNZL01 | 61.585.865/0001-51 | 6.999,99 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2017                  | 01/01/2020      | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 2                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 7,00      | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | 400         | % PAGTOS PONTUAIS     | 90                    | QTDE CONSULTAS MES ATUAL (M) | 125                       | QTDE CONSULTAS MES (M-1)     | 100                          |
      | BUNZL02 | 61.585.865/0001-51 | 7.000,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2020                  | 01/01/2020      | NÃO                | NÃO                | 1                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 1                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 0,00      | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | 399         | % PAGTOS PONTUAIS     | 89                    | QTDE CONSULTAS MES ATUAL (M) | 126                       | QTDE CONSULTAS MES (M-1)     | 100                          |
#      | BUNZL13 | 61.585.865/0001-51 | 7.000,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2020                  | 01/01/2020      | NÃO                | NÃO                | 1                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 1                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 1,00      | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           | % PAGTOS PONTUAIS     | 90                    | QTDE CONSULTAS MES ATUAL (M) | #                         | QTDE CONSULTAS MES (M-1)     | #                            |
#      | BUNZL14 | 61.585.865/0001-51 | 6.999,99 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2020                  | 01/01/2020      | NÃO                | NÃO                | 1                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 1                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 1,00      | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           | % PAGTOS PONTUAIS     | #                     | QTDE CONSULTAS MES ATUAL (M) | #                         | QTDE CONSULTAS MES (M-1)     | #                            |
#      | BUNZL15 | 61.585.865/0001-51 | 7.000,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2017                  | 01/01/2020      | NÃO                | NÃO                | 1                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 1                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 1,00      | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           | % PAGTOS PONTUAIS     | #                     | QTDE CONSULTAS MES ATUAL (M) | #                         | QTDE CONSULTAS MES (M-1)     | #                            |
#      | BUNZL16 | 61.585.865/0001-51 | 7.000,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2020                  | 01/01/2020      | NÃO                | NÃO                | 1                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 1                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 1,00      | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           | % PAGTOS PONTUAIS     | #                     | QTDE CONSULTAS MES ATUAL (M) | 125                       | QTDE CONSULTAS MES (M-1)     | 100                          |
#      | BUNZL17 | 61.585.865/0001-51 | 7.000,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2020                  | 01/01/2020      | NÃO                | NÃO                | 1                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 1                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 1,00      | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | 400         | % PAGTOS PONTUAIS     | #                     | QTDE CONSULTAS MES ATUAL (M) | #                         | QTDE CONSULTAS MES (M-1)     | #                            |
#      | BUNZL18 | 61.585.865/0001-51 | 7.000,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2020                  | 01/01/2020      | NÃO                | NÃO                | 1                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 2                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 1,00      | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           | % PAGTOS PONTUAIS     | #                     | QTDE CONSULTAS MES ATUAL (M) | #                         | QTDE CONSULTAS MES (M-1)     | #                            |
#      | BUNZL19 | 61.585.865/0001-51 | 7.000,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2020                  | 01/01/2020      | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 1                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 1,00      | 25/08/2020 | PONTUACAO DO SCORE (06 MESES) 22F | #           | % PAGTOS PONTUAIS     | #                     | QTDE CONSULTAS MES ATUAL (M) | #                         | QTDE CONSULTAS MES (M-1)     | #                            |


  Esquema do Cenário: Criar análise de crédito com sucesso "Regra de Comportamento" - <CT>
    Dado eu acesso a tela de análise de crédito
    E configuro a massa com os dados (Regra de Comportamento): "<CNPJ>","<DATA_ALT>","<CAMPO_PORTE_EMPRESA>","<VALOR_PORTE_EMPRESA>","<CAMPO_QTD_PROTESTOS>","<VALOR_QTD_PROTESTOS>","<CAMPO_VR_PROTESTOS>","<VALOR_VR_PROTESTOS>","<CAMPO_QTD_PEFIN>","<VALOR_QTD_PEFIN>","<CAMPO_VR_PEFIN>","<VALOR_VR_PEFIN>","<CAMPO_CONSULTAS_MES_ATUAL>","<VALOR_CONSULTAS_MES_ATUAL>","<CAMPO_CONSULTAS_MES_ANTERIOR>","<VALOR_CONSULTAS_MES_ANTERIOR>"
    Quando informo os seguintes dados on-line e clico em Analisar: "<CNPJ>","<VALOR_NF>","<AUTO_FALENCIA>","<CONCORDATA>","<CONCORDATA_DEFERIDA>","<CONCORDATA_REQUERIDA>","<CONCORDATA_SUSPENSIVA>","<DATA_ENTRADA_SOCIO_MAIS_RECENTE>","<DATA_DE_INICIO_DA_ATIVIDADE>","<DATA_DO_SISTEMA>","<FALENCIA_DECRETADA>","<FALENCIA_REQUERIDA>","<HISTORICO_DE_ATRASOS>","<MODALIDADE_DE_PAGAMENTO>","<PARTICIPACAO_EM_FALENCIA>","<QT_REFIN_BANCOS>","<RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA>","<RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA>","<RECUPERACAO_JUDICIAL_CONCEDIDA>","<RECUPERACAO_JUDICIAL_REQUERIDA>","<STATUS_CNPJ>","<TEMPO_RELACIONAMENTO>","<VALORES_EM_ABERTO>","<VR_REFIN_BANCOS_ATE_A_DATA>"
    Entao eu devo ver uma página com o resultado da análise: "<MSG_RESULTADO_ANALISE>", "<VALOR_NF>"
    E no relatório de Decisão de Crédito ter os seguintes dados on-line validados: "<CNPJ>","<VALOR_NF>","<AUTO_FALENCIA>","<CONCORDATA>","<CONCORDATA_DEFERIDA>","<CONCORDATA_REQUERIDA>","<CONCORDATA_SUSPENSIVA>","<DATA_ENTRADA_SOCIO_MAIS_RECENTE>","<DATA_DE_INICIO_DA_ATIVIDADE>","<DATA_DO_SISTEMA>","<FALENCIA_DECRETADA>","<FALENCIA_REQUERIDA>","<HISTORICO_DE_ATRASOS>","<MODALIDADE_DE_PAGAMENTO>","<PARTICIPACAO_EM_FALENCIA>","<QT_REFIN_BANCOS>","<RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA>","<RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA>","<RECUPERACAO_JUDICIAL_CONCEDIDA>","<RECUPERACAO_JUDICIAL_REQUERIDA>","<STATUS_CNPJ>","<TEMPO_RELACIONAMENTO>","<VALORES_EM_ABERTO>","<VR_REFIN_BANCOS_ATE_A_DATA>"
    E no relatório de Decisão de Crédito ter os seguintes dados (Regra de Comportamento) validados: "<VALOR_PORTE_EMPRESA>","<VALOR_QTD_PROTESTOS>","<VALOR_VR_PROTESTOS>","<VALOR_QTD_PEFIN>","<VALOR_VR_PEFIN>","<VALOR_CONSULTAS_MES_ATUAL>","<VALOR_CONSULTAS_MES_ANTERIOR>","<PONTUACAO>"

    Exemplos:
      | CT      | CNPJ               | VALOR_NF | AUTO_FALENCIA | CONCORDATA | CONCORDATA_DEFERIDA | CONCORDATA_REQUERIDA | CONCORDATA_SUSPENSIVA | DATA_ENTRADA_SOCIO_MAIS_RECENTE | DATA_DE_INICIO_DA_ATIVIDADE | DATA_DO_SISTEMA | FALENCIA_DECRETADA | FALENCIA_REQUERIDA | HISTORICO_DE_ATRASOS | MODALIDADE_DE_PAGAMENTO | PARTICIPACAO_EM_FALENCIA | QT_REFIN_BANCOS | RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA | RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA | RECUPERACAO_JUDICIAL_CONCEDIDA | RECUPERACAO_JUDICIAL_REQUERIDA | STATUS_CNPJ | TEMPO_RELACIONAMENTO | VALORES_EM_ABERTO | VR_REFIN_BANCOS_ATE_A_DATA | MSG_RESULTADO_ANALISE    | PONTUACAO | DATA_ALT   | CAMPO_CONSULTAS_MES_ATUAL    | VALOR_CONSULTAS_MES_ATUAL | CAMPO_CONSULTAS_MES_ANTERIOR | VALOR_CONSULTAS_MES_ANTERIOR | CAMPO_PORTE_EMPRESA | VALOR_PORTE_EMPRESA | CAMPO_QTD_PROTESTOS     | VALOR_QTD_PROTESTOS | CAMPO_VR_PROTESTOS      | VALOR_VR_PROTESTOS | CAMPO_QTD_PEFIN              | VALOR_QTD_PEFIN | CAMPO_VR_PEFIN               | VALOR_VR_PEFIN |
      | BUNZL01 | 61.585.865/0001-51 | 2.700,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2017                  | 17/09/2020      | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 3                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 30,00     | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 120                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | SMALL               | QT PROTESTOS ATE A DATA | 0                   | VR PROTESTOS ATE A DATA | 0,00               | QT PEFIN-EMPRESAS ATE A DATA | 0               | VR PEFIN-EMPRESAS ATE A DATA | 0,00           |
      | BUNZL02 | 61.585.865/0001-51 | 5.000,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2019                  | 17/09/2020      | NÃO                | NÃO                | 3                    | Depósito                | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 1                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 10,00     | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 150                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | SMALL+              | QT PROTESTOS ATE A DATA | 1                   | VR PROTESTOS ATE A DATA | 4.500,00           | QT PEFIN-EMPRESAS ATE A DATA | 1               | VR PEFIN-EMPRESAS ATE A DATA | 3.000,00       |
      | BUNZL03 | 61.585.865/0001-51 | 5.001,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2020                  | 17/09/2020      | NÃO                | NÃO                | 4                    | Outros                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 0,00      | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 151                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | SMALL               | QT PROTESTOS ATE A DATA | 2                   | VR PROTESTOS ATE A DATA | 4.501,00           | QT PEFIN-EMPRESAS ATE A DATA | 2               | VR PEFIN-EMPRESAS ATE A DATA | 3.001,00       |
      | BUNZL04 | 61.585.865/0001-51 | 3.500,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2017                  | 17/09/2020      | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 3                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 30,00     | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 120                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | MIDDLE              | QT PROTESTOS ATE A DATA | 3                   | VR PROTESTOS ATE A DATA | 30.000,00          | QT PEFIN-EMPRESAS ATE A DATA | 1               | VR PEFIN-EMPRESAS ATE A DATA | 7.000,00       |
      | BUNZL05 | 61.585.865/0001-51 | 5.500,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2019                  | 17/09/2020      | NÃO                | NÃO                | 3                    | Depósito                | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 1                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 10,00     | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 150                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | MIDDLE              | QT PROTESTOS ATE A DATA | 7                   | VR PROTESTOS ATE A DATA | 50.000,00          | QT PEFIN-EMPRESAS ATE A DATA | 3               | VR PEFIN-EMPRESAS ATE A DATA | 15.000,00      |
      | BUNZL06 | 61.585.865/0001-51 | 5.501,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2020                  | 17/09/2020      | NÃO                | NÃO                | 4                    | Outros                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 0,00      | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 151                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | MIDDLE+             | QT PROTESTOS ATE A DATA | 8                   | VR PROTESTOS ATE A DATA | 51.000,00          | QT PEFIN-EMPRESAS ATE A DATA | 4               | VR PEFIN-EMPRESAS ATE A DATA | 15.001,00      |
      | BUNZL07 | 61.585.865/0001-51 | 3.500,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2017                  | 17/09/2020      | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 3                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 30,00     | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 120                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | CORPORATE           | QT PROTESTOS ATE A DATA | 20                  | VR PROTESTOS ATE A DATA | 300.000,00         | QT PEFIN-EMPRESAS ATE A DATA | 10              | VR PEFIN-EMPRESAS ATE A DATA | 70.000,00      |
      | BUNZL08 | 61.585.865/0001-51 | 5.500,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2019                  | 17/09/2020      | NÃO                | NÃO                | 3                    | Depósito                | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 1                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 10,00     | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 150                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | CORPORATE           | QT PROTESTOS ATE A DATA | 35                  | VR PROTESTOS ATE A DATA | 500.000,00         | QT PEFIN-EMPRESAS ATE A DATA | 25              | VR PEFIN-EMPRESAS ATE A DATA | 120.000,00     |
      | BUNZL09 | 61.585.865/0001-51 | 5.501,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2020                  | 17/09/2020      | NÃO                | NÃO                | 4                    | Outros                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 0,00      | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 151                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | CORPORATE           | QT PROTESTOS ATE A DATA | 36                  | VR PROTESTOS ATE A DATA | 500.001,00         | QT PEFIN-EMPRESAS ATE A DATA | 26              | VR PEFIN-EMPRESAS ATE A DATA | 120.001,00     |
      | BUNZL10 | 61.585.865/0001-51 | 3.500,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2017                  | 17/09/2020      | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 3                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 30,00     | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 120                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | #                   | QT PROTESTOS ATE A DATA | 9                   | VR PROTESTOS ATE A DATA | 70.000,00          | QT PEFIN-EMPRESAS ATE A DATA | 2               | VR PEFIN-EMPRESAS ATE A DATA | 10.000,00      |
      | BUNZL11 | 61.585.865/0001-51 | 5.500,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2019                  | 17/09/2020      | NÃO                | NÃO                | 3                    | Depósito                | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 1                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 10,00     | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 150                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | #                   | QT PROTESTOS ATE A DATA | 20                  | VR PROTESTOS ATE A DATA | 170.000,00         | QT PEFIN-EMPRESAS ATE A DATA | 5               | VR PEFIN-EMPRESAS ATE A DATA | 20.000,00      |
      | BUNZL12 | 61.585.865/0001-51 | 5.501,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2020                  | 17/09/2020      | NÃO                | NÃO                | 4                    | Outros                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 0,00      | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 151                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | #                   | QT PROTESTOS ATE A DATA | 21                  | VR PROTESTOS ATE A DATA | 170.001,00         | QT PEFIN-EMPRESAS ATE A DATA | 6               | VR PEFIN-EMPRESAS ATE A DATA | 20.001,00      |


  Esquema do Cenário: Criar análise de crédito com sucesso "Pontos de Corte Score 6.0" - <CT>
    Dado eu acesso a tela de análise de crédito
    E configuro a massa com os dados (Pontos de Corte Score 6.0): "<CNPJ>","<DATA_ALT>","<CAMPO_PORTE_EMPRESA>","<VALOR_PORTE_EMPRESA>","<CAMPO_SCORE>","<VALOR_SCORE>"
    Quando informo os seguintes dados on-line e clico em Analisar: "<CNPJ>","<VALOR_NF>","<AUTO_FALENCIA>","<CONCORDATA>","<CONCORDATA_DEFERIDA>","<CONCORDATA_REQUERIDA>","<CONCORDATA_SUSPENSIVA>","<DATA_ENTRADA_SOCIO_MAIS_RECENTE>","<DATA_DE_INICIO_DA_ATIVIDADE>","<DATA_DO_SISTEMA>","<FALENCIA_DECRETADA>","<FALENCIA_REQUERIDA>","<HISTORICO_DE_ATRASOS>","<MODALIDADE_DE_PAGAMENTO>","<PARTICIPACAO_EM_FALENCIA>","<QT_REFIN_BANCOS>","<RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA>","<RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA>","<RECUPERACAO_JUDICIAL_CONCEDIDA>","<RECUPERACAO_JUDICIAL_REQUERIDA>","<STATUS_CNPJ>","<TEMPO_RELACIONAMENTO>","<VALORES_EM_ABERTO>","<VR_REFIN_BANCOS_ATE_A_DATA>"
    Entao eu devo ver uma página com o resultado da análise: "<MSG_RESULTADO_ANALISE>", "<VALOR_NF>"
    E no relatório de Decisão de Crédito ter os seguintes dados on-line validados: "<CNPJ>","<VALOR_NF>","<AUTO_FALENCIA>","<CONCORDATA>","<CONCORDATA_DEFERIDA>","<CONCORDATA_REQUERIDA>","<CONCORDATA_SUSPENSIVA>","<DATA_ENTRADA_SOCIO_MAIS_RECENTE>","<DATA_DE_INICIO_DA_ATIVIDADE>","<DATA_DO_SISTEMA>","<FALENCIA_DECRETADA>","<FALENCIA_REQUERIDA>","<HISTORICO_DE_ATRASOS>","<MODALIDADE_DE_PAGAMENTO>","<PARTICIPACAO_EM_FALENCIA>","<QT_REFIN_BANCOS>","<RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA>","<RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA>","<RECUPERACAO_JUDICIAL_CONCEDIDA>","<RECUPERACAO_JUDICIAL_REQUERIDA>","<STATUS_CNPJ>","<TEMPO_RELACIONAMENTO>","<VALORES_EM_ABERTO>","<VR_REFIN_BANCOS_ATE_A_DATA>"
    E no relatório de Decisão de Crédito ter os seguintes dados (Pontos de Corte Score 6.0) validados: "<VALOR_PORTE_EMPRESA>","<VALOR_SCORE>","<PONTUACAO>","<RISCO>"

    Exemplos:
      | CT      | CNPJ               | VALOR_NF | AUTO_FALENCIA | CONCORDATA | CONCORDATA_DEFERIDA | CONCORDATA_REQUERIDA | CONCORDATA_SUSPENSIVA | DATA_ENTRADA_SOCIO_MAIS_RECENTE | DATA_DE_INICIO_DA_ATIVIDADE | DATA_DO_SISTEMA | FALENCIA_DECRETADA | FALENCIA_REQUERIDA | HISTORICO_DE_ATRASOS | MODALIDADE_DE_PAGAMENTO | PARTICIPACAO_EM_FALENCIA | QT_REFIN_BANCOS | RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA | RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA | RECUPERACAO_JUDICIAL_CONCEDIDA | RECUPERACAO_JUDICIAL_REQUERIDA | STATUS_CNPJ | TEMPO_RELACIONAMENTO | VALORES_EM_ABERTO | VR_REFIN_BANCOS_ATE_A_DATA | MSG_RESULTADO_ANALISE    | PONTUACAO | RISCO | DATA_ALT   | CAMPO_PORTE_EMPRESA | VALOR_PORTE_EMPRESA | CAMPO_SCORE                       | VALOR_SCORE |
      | BUNZL01 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA |           | BAIXO | 25/08/2020 | PORTE DA EMPRESA    | SMALL               | PONTUACAO DO SCORE (06 MESES) 22F | 701         |
      | BUNZL02 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA |           | MEDIO | 25/08/2020 | PORTE DA EMPRESA    | SMALL+              | PONTUACAO DO SCORE (06 MESES) 22F | 700         |
      | BUNZL03 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA |           | ALTO  | 25/08/2020 | PORTE DA EMPRESA    | SMALL               | PONTUACAO DO SCORE (06 MESES) 22F | 400         |
      | BUNZL04 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA |           | BAIXO | 25/08/2020 | PORTE DA EMPRESA    | MIDDLE              | PONTUACAO DO SCORE (06 MESES) 22F | 701         |
      | BUNZL05 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA |           | MEDIO | 25/08/2020 | PORTE DA EMPRESA    | MIDDLE              | PONTUACAO DO SCORE (06 MESES) 22F | 700         |
      | BUNZL06 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA |           | ALTO  | 25/08/2020 | PORTE DA EMPRESA    | MIDDLE+             | PONTUACAO DO SCORE (06 MESES) 22F | 300         |
      | BUNZL07 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA |           | BAIXO | 25/08/2020 | PORTE DA EMPRESA    | CORPORATE           | PONTUACAO DO SCORE (06 MESES) 22F | 601         |
      | BUNZL08 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA |           | MEDIO | 25/08/2020 | PORTE DA EMPRESA    | CORPORATE+          | PONTUACAO DO SCORE (06 MESES) 22F | 600         |
      | BUNZL09 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA |           | ALTO  | 25/08/2020 | PORTE DA EMPRESA    | CORPORATE           | PONTUACAO DO SCORE (06 MESES) 22F | 300         |
      | BUNZL10 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA |           | BAIXO | 25/08/2020 | PORTE DA EMPRESA    | #                   | PONTUACAO DO SCORE (06 MESES) 22F | 701         |
      | BUNZL11 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA |           | MEDIO | 25/08/2020 | PORTE DA EMPRESA    | #                   | PONTUACAO DO SCORE (06 MESES) 22F | 700         |
      | BUNZL12 | 61.585.865/0001-51 | 100,00   | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA |           | ALTO  | 25/08/2020 | PORTE DA EMPRESA    | #                   | PONTUACAO DO SCORE (06 MESES) 22F | 400         |

  Esquema do Cenário: Criar análise de crédito com sucesso "Clientes Corporate+" - <CT>
    Dado eu acesso a tela de análise de crédito
    E configuro a massa com os dados (Clientes Corporate Plus): "<CNPJ>","<DATA_ALT>","<CAMPO_PORTE_EMPRESA>","<VALOR_PORTE_EMPRESA>","<CAMPO_PAGTOS_PONTUAIS>","<VALOR_PAGTOS_PONTUAIS>","<CAMPO_QTD_PROTESTOS>","<VALOR_QTD_PROTESTOS>","<CAMPO_QTD_PEFIN>","<VALOR_QTD_PEFIN>","<CAMPO_CAPITAL_SOCIAL>","<VALOR_CAPITAL_SOCIAL>"
    Quando informo os seguintes dados on-line e clico em Analisar: "<CNPJ>","<VALOR_NF>","<AUTO_FALENCIA>","<CONCORDATA>","<CONCORDATA_DEFERIDA>","<CONCORDATA_REQUERIDA>","<CONCORDATA_SUSPENSIVA>","<DATA_ENTRADA_SOCIO_MAIS_RECENTE>","<DATA_DE_INICIO_DA_ATIVIDADE>","<DATA_DO_SISTEMA>","<FALENCIA_DECRETADA>","<FALENCIA_REQUERIDA>","<HISTORICO_DE_ATRASOS>","<MODALIDADE_DE_PAGAMENTO>","<PARTICIPACAO_EM_FALENCIA>","<QT_REFIN_BANCOS>","<RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA>","<RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA>","<RECUPERACAO_JUDICIAL_CONCEDIDA>","<RECUPERACAO_JUDICIAL_REQUERIDA>","<STATUS_CNPJ>","<TEMPO_RELACIONAMENTO>","<VALORES_EM_ABERTO>","<VR_REFIN_BANCOS_ATE_A_DATA>"
    Entao eu devo ver uma página com o resultado da análise: "<MSG_RESULTADO_ANALISE>", "<VALOR_NF>"
    E no relatório de Decisão de Crédito ter os seguintes dados on-line validados: "<CNPJ>","<VALOR_NF>","<AUTO_FALENCIA>","<CONCORDATA>","<CONCORDATA_DEFERIDA>","<CONCORDATA_REQUERIDA>","<CONCORDATA_SUSPENSIVA>","<DATA_ENTRADA_SOCIO_MAIS_RECENTE>","<DATA_DE_INICIO_DA_ATIVIDADE>","<DATA_DO_SISTEMA>","<FALENCIA_DECRETADA>","<FALENCIA_REQUERIDA>","<HISTORICO_DE_ATRASOS>","<MODALIDADE_DE_PAGAMENTO>","<PARTICIPACAO_EM_FALENCIA>","<QT_REFIN_BANCOS>","<RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA>","<RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA>","<RECUPERACAO_JUDICIAL_CONCEDIDA>","<RECUPERACAO_JUDICIAL_REQUERIDA>","<STATUS_CNPJ>","<TEMPO_RELACIONAMENTO>","<VALORES_EM_ABERTO>","<VR_REFIN_BANCOS_ATE_A_DATA>"
    E no relatório de Decisão de Crédito ter os seguintes dados (Clientes Corporate Plus) validados: "<VALOR_PORTE_EMPRESA>","<VALOR_PAGTOS_PONTUAIS>","<VALOR_QTD_PROTESTOS>","<VALOR_QTD_PEFIN>","<VALOR_CAPITAL_SOCIAL>","<PONTUACAO>"

    Exemplos:
      | CT      | CNPJ               | VALOR_NF | AUTO_FALENCIA | CONCORDATA | CONCORDATA_DEFERIDA | CONCORDATA_REQUERIDA | CONCORDATA_SUSPENSIVA | DATA_ENTRADA_SOCIO_MAIS_RECENTE | DATA_DE_INICIO_DA_ATIVIDADE | DATA_DO_SISTEMA | FALENCIA_DECRETADA | FALENCIA_REQUERIDA | HISTORICO_DE_ATRASOS | MODALIDADE_DE_PAGAMENTO | PARTICIPACAO_EM_FALENCIA | QT_REFIN_BANCOS | RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA | RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA | RECUPERACAO_JUDICIAL_CONCEDIDA | RECUPERACAO_JUDICIAL_REQUERIDA | STATUS_CNPJ | TEMPO_RELACIONAMENTO | VALORES_EM_ABERTO | VR_REFIN_BANCOS_ATE_A_DATA | MSG_RESULTADO_ANALISE    | PONTUACAO | DATA_ALT   | CAMPO_PORTE_EMPRESA | VALOR_PORTE_EMPRESA | CAMPO_PAGTOS_PONTUAIS | VALOR_PAGTOS_PONTUAIS | CAMPO_QTD_PROTESTOS     | VALOR_QTD_PROTESTOS | CAMPO_QTD_PEFIN              | VALOR_QTD_PEFIN | CAMPO_CAPITAL_SOCIAL | VALOR_CAPITAL_SOCIAL |
      | BUNZL01 | 61.585.865/0001-51 | 2.700,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | #                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 5                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 15,00     | 25/08/2020 | PORTE DA EMPRESA    | CORPORATE+          | % PAGTOS PONTUAIS     | 100                   | QT PROTESTOS ATE A DATA | 30                  | QT PEFIN-EMPRESAS ATE A DATA | 20              | CAPITAL SOCIAL       | 1000000,00           |
      | BUNZL02 | 61.585.865/0001-51 | 2.700,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | #                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 2                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 5,00      | 25/08/2020 | PORTE DA EMPRESA    | CORPORATE+          | % PAGTOS PONTUAIS     | 80                    | QT PROTESTOS ATE A DATA | 100                 | QT PEFIN-EMPRESAS ATE A DATA | 50              | CAPITAL SOCIAL       | 600000,00            |
      | BUNZL03 | 61.585.865/0001-51 | 2.700,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | #                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 1                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 0,00      | 25/08/2020 | PORTE DA EMPRESA    | CORPORATE+          | % PAGTOS PONTUAIS     | 79                    | QT PROTESTOS ATE A DATA | 101                 | QT PEFIN-EMPRESAS ATE A DATA | 51              | CAPITAL SOCIAL       | 599999,00            |


  Esquema do Cenário: Criar análise de crédito com sucesso "Classificação Final" - <CT>
    Dado eu acesso a tela de análise de crédito
    E configuro a massa com os dados (Classificação Final): "<CNPJ>","<DATA_ALT>","<CAMPO_PORTE_EMPRESA>","<VALOR_PORTE_EMPRESA>","<CAMPO_QTD_PROTESTOS>","<VALOR_QTD_PROTESTOS>","<CAMPO_VR_PROTESTOS>","<VALOR_VR_PROTESTOS>","<CAMPO_QTD_PEFIN>","<VALOR_QTD_PEFIN>","<CAMPO_VR_PEFIN>","<VALOR_VR_PEFIN>","<CAMPO_CONSULTAS_MES_ATUAL>","<VALOR_CONSULTAS_MES_ATUAL>","<CAMPO_CONSULTAS_MES_ANTERIOR>","<VALOR_CONSULTAS_MES_ANTERIOR>","<CAMPO_SCORE>", "<VALOR_SCORE>"
    Quando informo os seguintes dados on-line e clico em Analisar: "<CNPJ>","<VALOR_NF>","<AUTO_FALENCIA>","<CONCORDATA>","<CONCORDATA_DEFERIDA>","<CONCORDATA_REQUERIDA>","<CONCORDATA_SUSPENSIVA>","<DATA_ENTRADA_SOCIO_MAIS_RECENTE>","<DATA_DE_INICIO_DA_ATIVIDADE>","<DATA_DO_SISTEMA>","<FALENCIA_DECRETADA>","<FALENCIA_REQUERIDA>","<HISTORICO_DE_ATRASOS>","<MODALIDADE_DE_PAGAMENTO>","<PARTICIPACAO_EM_FALENCIA>","<QT_REFIN_BANCOS>","<RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA>","<RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA>","<RECUPERACAO_JUDICIAL_CONCEDIDA>","<RECUPERACAO_JUDICIAL_REQUERIDA>","<STATUS_CNPJ>","<TEMPO_RELACIONAMENTO>","<VALORES_EM_ABERTO>","<VR_REFIN_BANCOS_ATE_A_DATA>"
    Entao eu devo ver uma página com o resultado da análise: "<MSG_RESULTADO_ANALISE>", "<VALOR_NF>"
    E no relatório de Decisão de Crédito ter os seguintes dados on-line validados: "<CNPJ>","<VALOR_NF>","<AUTO_FALENCIA>","<CONCORDATA>","<CONCORDATA_DEFERIDA>","<CONCORDATA_REQUERIDA>","<CONCORDATA_SUSPENSIVA>","<DATA_ENTRADA_SOCIO_MAIS_RECENTE>","<DATA_DE_INICIO_DA_ATIVIDADE>","<DATA_DO_SISTEMA>","<FALENCIA_DECRETADA>","<FALENCIA_REQUERIDA>","<HISTORICO_DE_ATRASOS>","<MODALIDADE_DE_PAGAMENTO>","<PARTICIPACAO_EM_FALENCIA>","<QT_REFIN_BANCOS>","<RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA>","<RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA>","<RECUPERACAO_JUDICIAL_CONCEDIDA>","<RECUPERACAO_JUDICIAL_REQUERIDA>","<STATUS_CNPJ>","<TEMPO_RELACIONAMENTO>","<VALORES_EM_ABERTO>","<VR_REFIN_BANCOS_ATE_A_DATA>"
    E no relatório de Decisão de Crédito ter os seguintes dados (Classificação Final) validados: "<VALOR_PORTE_EMPRESA>","<VALOR_QTD_PROTESTOS>","<VALOR_VR_PROTESTOS>","<VALOR_QTD_PEFIN>","<VALOR_VR_PEFIN>","<VALOR_CONSULTAS_MES_ATUAL>","<VALOR_CONSULTAS_MES_ANTERIOR>","<PONTUACAO>","<VALOR_SCORE>"

    Exemplos:
      | CT      | CNPJ               | VALOR_NF | AUTO_FALENCIA | CONCORDATA | CONCORDATA_DEFERIDA | CONCORDATA_REQUERIDA | CONCORDATA_SUSPENSIVA | DATA_ENTRADA_SOCIO_MAIS_RECENTE | DATA_DE_INICIO_DA_ATIVIDADE | DATA_DO_SISTEMA | FALENCIA_DECRETADA | FALENCIA_REQUERIDA | HISTORICO_DE_ATRASOS | MODALIDADE_DE_PAGAMENTO | PARTICIPACAO_EM_FALENCIA | QT_REFIN_BANCOS | RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA | RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA | RECUPERACAO_JUDICIAL_CONCEDIDA | RECUPERACAO_JUDICIAL_REQUERIDA | STATUS_CNPJ | TEMPO_RELACIONAMENTO | VALORES_EM_ABERTO | VR_REFIN_BANCOS_ATE_A_DATA | MSG_RESULTADO_ANALISE                                              | PONTUACAO | DATA_ALT   | CAMPO_CONSULTAS_MES_ATUAL    | VALOR_CONSULTAS_MES_ATUAL | CAMPO_CONSULTAS_MES_ANTERIOR | VALOR_CONSULTAS_MES_ANTERIOR | CAMPO_PORTE_EMPRESA | VALOR_PORTE_EMPRESA | CAMPO_QTD_PROTESTOS     | VALOR_QTD_PROTESTOS | CAMPO_VR_PROTESTOS      | VALOR_VR_PROTESTOS | CAMPO_QTD_PEFIN              | VALOR_QTD_PEFIN | CAMPO_VR_PEFIN               | VALOR_VR_PEFIN | CAMPO_SCORE                       | VALOR_SCORE |
      | BUNZL01 | 61.585.865/0001-51 | 2.700,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2017                  | 01/01/2020      | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 3                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA                                           | 30,00     | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 120                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | SMALL               | QT PROTESTOS ATE A DATA | 0                   | VR PROTESTOS ATE A DATA | 0,00               | QT PEFIN-EMPRESAS ATE A DATA | 0               | VR PEFIN-EMPRESAS ATE A DATA | 0,00           | PONTUACAO DO SCORE (06 MESES) 22F | 900         |
      | BUNZL02 | 61.585.865/0001-51 | 5.000,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2019                  | 01/01/2020      | NÃO                | NÃO                | 3                    | Depósito                | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 2                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA                                           | 10,00     | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 125                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | #                   | QT PROTESTOS ATE A DATA | 10                  | VR PROTESTOS ATE A DATA | 71.000,00          | QT PEFIN-EMPRESAS ATE A DATA | 5               | VR PEFIN-EMPRESAS ATE A DATA | 11.000,00      | PONTUACAO DO SCORE (06 MESES) 22F | 300         |
      | BUNZL03 | 61.585.865/0001-51 | 6.999,99 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2020                  | 01/01/2020      | NÃO                | NÃO                | 4                    | Outros                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA: ALTÍSSIMO RISCO - NEGADO (VENDA A VISTA) | 0,00      | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 175                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | MIDDLE              | QT PROTESTOS ATE A DATA | 8                   | VR PROTESTOS ATE A DATA | 51.000,00          | QT PEFIN-EMPRESAS ATE A DATA | 4               | VR PEFIN-EMPRESAS ATE A DATA | 16.000,00      | PONTUACAO DO SCORE (06 MESES) 22F | 400         |


  Esquema do Cenário: Criar análise de crédito com sucesso "Risco Final Clientes Corporate+" - <CT>
    Dado eu acesso a tela de análise de crédito
    E configuro a massa com os dados (Risco Final Clientes Corporate Plus): "<CNPJ>","<DATA_ALT>","<CAMPO_PORTE_EMPRESA>","<VALOR_PORTE_EMPRESA>","<CAMPO_PAGTOS_PONTUAIS>","<VALOR_PAGTOS_PONTUAIS>","<CAMPO_QTD_PROTESTOS>","<VALOR_QTD_PROTESTOS>","<CAMPO_QTD_PEFIN>","<VALOR_QTD_PEFIN>","<CAMPO_CAPITAL_SOCIAL>","<VALOR_CAPITAL_SOCIAL>","<CAMPO_SCORE>", "<VALOR_SCORE>"
    Quando informo os seguintes dados on-line e clico em Analisar: "<CNPJ>","<VALOR_NF>","<AUTO_FALENCIA>","<CONCORDATA>","<CONCORDATA_DEFERIDA>","<CONCORDATA_REQUERIDA>","<CONCORDATA_SUSPENSIVA>","<DATA_ENTRADA_SOCIO_MAIS_RECENTE>","<DATA_DE_INICIO_DA_ATIVIDADE>","<DATA_DO_SISTEMA>","<FALENCIA_DECRETADA>","<FALENCIA_REQUERIDA>","<HISTORICO_DE_ATRASOS>","<MODALIDADE_DE_PAGAMENTO>","<PARTICIPACAO_EM_FALENCIA>","<QT_REFIN_BANCOS>","<RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA>","<RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA>","<RECUPERACAO_JUDICIAL_CONCEDIDA>","<RECUPERACAO_JUDICIAL_REQUERIDA>","<STATUS_CNPJ>","<TEMPO_RELACIONAMENTO>","<VALORES_EM_ABERTO>","<VR_REFIN_BANCOS_ATE_A_DATA>"
    Entao eu devo ver uma página com o resultado da análise: "<MSG_RESULTADO_ANALISE>", "<VALOR_NF>"
    E no relatório de Decisão de Crédito ter os seguintes dados on-line validados: "<CNPJ>","<VALOR_NF>","<AUTO_FALENCIA>","<CONCORDATA>","<CONCORDATA_DEFERIDA>","<CONCORDATA_REQUERIDA>","<CONCORDATA_SUSPENSIVA>","<DATA_ENTRADA_SOCIO_MAIS_RECENTE>","<DATA_DE_INICIO_DA_ATIVIDADE>","<DATA_DO_SISTEMA>","<FALENCIA_DECRETADA>","<FALENCIA_REQUERIDA>","<HISTORICO_DE_ATRASOS>","<MODALIDADE_DE_PAGAMENTO>","<PARTICIPACAO_EM_FALENCIA>","<QT_REFIN_BANCOS>","<RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA>","<RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA>","<RECUPERACAO_JUDICIAL_CONCEDIDA>","<RECUPERACAO_JUDICIAL_REQUERIDA>","<STATUS_CNPJ>","<TEMPO_RELACIONAMENTO>","<VALORES_EM_ABERTO>","<VR_REFIN_BANCOS_ATE_A_DATA>"
    E no relatório de Decisão de Crédito ter os seguintes dados (Risco Final Clientes Corporate Plus) validados: "<VALOR_PORTE_EMPRESA>","<VALOR_PAGTOS_PONTUAIS>","<VALOR_QTD_PROTESTOS>","<VALOR_QTD_PEFIN>","<VALOR_CAPITAL_SOCIAL>","<PONTUACAO>","<VALOR_SCORE>"

    Exemplos:
      | CT      | CNPJ               | VALOR_NF | AUTO_FALENCIA | CONCORDATA | CONCORDATA_DEFERIDA | CONCORDATA_REQUERIDA | CONCORDATA_SUSPENSIVA | DATA_ENTRADA_SOCIO_MAIS_RECENTE | DATA_DE_INICIO_DA_ATIVIDADE | DATA_DO_SISTEMA | FALENCIA_DECRETADA | FALENCIA_REQUERIDA | HISTORICO_DE_ATRASOS | MODALIDADE_DE_PAGAMENTO | PARTICIPACAO_EM_FALENCIA | QT_REFIN_BANCOS | RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA | RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA | RECUPERACAO_JUDICIAL_CONCEDIDA | RECUPERACAO_JUDICIAL_REQUERIDA | STATUS_CNPJ | TEMPO_RELACIONAMENTO | VALORES_EM_ABERTO | VR_REFIN_BANCOS_ATE_A_DATA | MSG_RESULTADO_ANALISE    | PONTUACAO | DATA_ALT   | CAMPO_PORTE_EMPRESA | VALOR_PORTE_EMPRESA | CAMPO_PAGTOS_PONTUAIS | VALOR_PAGTOS_PONTUAIS | CAMPO_QTD_PROTESTOS     | VALOR_QTD_PROTESTOS | CAMPO_QTD_PEFIN              | VALOR_QTD_PEFIN | CAMPO_CAPITAL_SOCIAL | VALOR_CAPITAL_SOCIAL | CAMPO_SCORE                       | VALOR_SCORE |
      | BUNZL01 | 61.585.865/0001-51 | 2.700,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | #                           | #               | NÃO                | NÃO                | #                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 6                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 15,00     | 25/08/2020 | PORTE DA EMPRESA    | CORPORATE+          | % PAGTOS PONTUAIS     | 100                   | QT PROTESTOS ATE A DATA | 30                  | QT PEFIN-EMPRESAS ATE A DATA | 20              | CAPITAL SOCIAL       | 1000000,00           | PONTUACAO DO SCORE (06 MESES) 22F | 900         |

  Esquema do Cenário: Criar análise de crédito com sucesso "Limite Disponível" - <CT>
    Dado eu acesso a tela de análise de crédito
    E configuro a massa com os dados (Limite Disponível): "<CNPJ>","<DATA_ALT>","<CAMPO_PORTE_EMPRESA>","<VALOR_PORTE_EMPRESA>","<CAMPO_QTD_PROTESTOS>","<VALOR_QTD_PROTESTOS>","<CAMPO_VR_PROTESTOS>","<VALOR_VR_PROTESTOS>","<CAMPO_QTD_PEFIN>","<VALOR_QTD_PEFIN>","<CAMPO_VR_PEFIN>","<VALOR_VR_PEFIN>","<CAMPO_CONSULTAS_MES_ATUAL>","<VALOR_CONSULTAS_MES_ATUAL>","<CAMPO_CONSULTAS_MES_ANTERIOR>","<VALOR_CONSULTAS_MES_ANTERIOR>","<CAMPO_SCORE>", "<VALOR_SCORE>","<CAMPO_FATURAMENTO_PRESUMIDO>","<VALOR_FATURAMENTO_PRESUMIDO>","<CAMPO_CAPITAL_SOCIAL>","<VALOR_CAPITAL_SOCIAL>"
    Quando informo os seguintes dados on-line e clico em Analisar: "<CNPJ>","<VALOR_NF>","<AUTO_FALENCIA>","<CONCORDATA>","<CONCORDATA_DEFERIDA>","<CONCORDATA_REQUERIDA>","<CONCORDATA_SUSPENSIVA>","<DATA_ENTRADA_SOCIO_MAIS_RECENTE>","<DATA_DE_INICIO_DA_ATIVIDADE>","<DATA_DO_SISTEMA>","<FALENCIA_DECRETADA>","<FALENCIA_REQUERIDA>","<HISTORICO_DE_ATRASOS>","<MODALIDADE_DE_PAGAMENTO>","<PARTICIPACAO_EM_FALENCIA>","<QT_REFIN_BANCOS>","<RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA>","<RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA>","<RECUPERACAO_JUDICIAL_CONCEDIDA>","<RECUPERACAO_JUDICIAL_REQUERIDA>","<STATUS_CNPJ>","<TEMPO_RELACIONAMENTO>","<VALORES_EM_ABERTO>","<VR_REFIN_BANCOS_ATE_A_DATA>"
    Entao eu devo ver uma página com o resultado da análise: "<MSG_RESULTADO_ANALISE>", "<VALOR_NF>"
    E no relatório de Decisão de Crédito ter os seguintes dados on-line validados: "<CNPJ>","<VALOR_NF>","<AUTO_FALENCIA>","<CONCORDATA>","<CONCORDATA_DEFERIDA>","<CONCORDATA_REQUERIDA>","<CONCORDATA_SUSPENSIVA>","<DATA_ENTRADA_SOCIO_MAIS_RECENTE>","<DATA_DE_INICIO_DA_ATIVIDADE>","<DATA_DO_SISTEMA>","<FALENCIA_DECRETADA>","<FALENCIA_REQUERIDA>","<HISTORICO_DE_ATRASOS>","<MODALIDADE_DE_PAGAMENTO>","<PARTICIPACAO_EM_FALENCIA>","<QT_REFIN_BANCOS>","<RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA>","<RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA>","<RECUPERACAO_JUDICIAL_CONCEDIDA>","<RECUPERACAO_JUDICIAL_REQUERIDA>","<STATUS_CNPJ>","<TEMPO_RELACIONAMENTO>","<VALORES_EM_ABERTO>","<VR_REFIN_BANCOS_ATE_A_DATA>"
    E no relatório de Decisão de Crédito ter os seguintes dados (Limite Disponível) validados: "<VALOR_PORTE_EMPRESA>","<VALOR_QTD_PROTESTOS>","<VALOR_VR_PROTESTOS>","<VALOR_QTD_PEFIN>","<VALOR_VR_PEFIN>","<VALOR_CONSULTAS_MES_ATUAL>","<VALOR_CONSULTAS_MES_ANTERIOR>","<PONTUACAO>","<VALOR_SCORE>","<VALOR_FATURAMENTO_PRESUMIDO>","<VALOR_CAPITAL_SOCIAL>"

    Exemplos:
      | CT      | CNPJ               | VALOR_NF | AUTO_FALENCIA | CONCORDATA | CONCORDATA_DEFERIDA | CONCORDATA_REQUERIDA | CONCORDATA_SUSPENSIVA | DATA_ENTRADA_SOCIO_MAIS_RECENTE | DATA_DE_INICIO_DA_ATIVIDADE | DATA_DO_SISTEMA | FALENCIA_DECRETADA | FALENCIA_REQUERIDA | HISTORICO_DE_ATRASOS | MODALIDADE_DE_PAGAMENTO | PARTICIPACAO_EM_FALENCIA | QT_REFIN_BANCOS | RECUPERACAO_EXTRA_JUDICIAL_HOMOLOGADA | RECUPERACAO_EXTRA_JUDICIAL_REQUERIDA | RECUPERACAO_JUDICIAL_CONCEDIDA | RECUPERACAO_JUDICIAL_REQUERIDA | STATUS_CNPJ | TEMPO_RELACIONAMENTO | VALORES_EM_ABERTO | VR_REFIN_BANCOS_ATE_A_DATA | MSG_RESULTADO_ANALISE    | PONTUACAO | DATA_ALT   | CAMPO_CONSULTAS_MES_ATUAL    | VALOR_CONSULTAS_MES_ATUAL | CAMPO_CONSULTAS_MES_ANTERIOR | VALOR_CONSULTAS_MES_ANTERIOR | CAMPO_PORTE_EMPRESA | VALOR_PORTE_EMPRESA | CAMPO_QTD_PROTESTOS     | VALOR_QTD_PROTESTOS | CAMPO_VR_PROTESTOS      | VALOR_VR_PROTESTOS | CAMPO_QTD_PEFIN              | VALOR_QTD_PEFIN | CAMPO_VR_PEFIN               | VALOR_VR_PEFIN | CAMPO_SCORE                       | VALOR_SCORE | CAMPO_FATURAMENTO_PRESUMIDO | VALOR_FATURAMENTO_PRESUMIDO | CAMPO_CAPITAL_SOCIAL | VALOR_CAPITAL_SOCIAL |
#      | BUNZL01 | 61.585.865/0001-51 | 2.700,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2017                  | 01/01/2020      | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 3                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 30,00     | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 120                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | SMALL               | QT PROTESTOS ATE A DATA | 0                   | VR PROTESTOS ATE A DATA | 0,00               | QT PEFIN-EMPRESAS ATE A DATA | 0               | VR PEFIN-EMPRESAS ATE A DATA | 0,00           | PONTUACAO DO SCORE (06 MESES) 22F | 900         | FATURAMENTO PRESUMIDO 1.0   | #                           | CAPITAL SOCIAL       | 100000,00            |
      | BUNZL02 | 61.585.865/0001-51 | 1.000,00 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2010                  | 01/01/2020      | NÃO                | NÃO                | 0                    | Boleto                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 5                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 10,00     | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 120                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | MIDDLE              | QT PROTESTOS ATE A DATA | 0                   | VR PROTESTOS ATE A DATA | 0,00               | QT PEFIN-EMPRESAS ATE A DATA | 0               | VR PEFIN-EMPRESAS ATE A DATA | 0,00           | PONTUACAO DO SCORE (06 MESES) 22F | 700         | FATURAMENTO PRESUMIDO 1.0   | 550000,00                   | CAPITAL SOCIAL       | 100000,00            |
#      | BUNZL03 | 61.585.865/0001-51 | 6.999,99 | NÃO           | NÃO        | NÃO                 | NÃO                  | NÃO                   | #                               | 01/01/2020                  | 01/01/2020      | NÃO                | NÃO                | 4                    | Outros                  | NÃO                      | #               | NÃO                                   | NÃO                                  | NÃO                            | NÃO                            | ATIVO       | 0                    | 0,00              | #                          | RECOMENDAÇÃO DA POLÍTICA | 0,00      | 25/08/2020 | QTDE CONSULTAS MES ATUAL (M) | 175                       | QTDE CONSULTAS MES (M-1)     | 100                          | PORTE DA EMPRESA    | MIDDLE              | QT PROTESTOS ATE A DATA | 8                   | VR PROTESTOS ATE A DATA | 51.000,00          | QT PEFIN-EMPRESAS ATE A DATA | 4               | VR PEFIN-EMPRESAS ATE A DATA | 16.000,00      | PONTUACAO DO SCORE (06 MESES) 22F | 400         |                             |                             |                      |                      |









